### ISSUE TITLE
 Failed to build GCC part 1 (stage: gcc_build) On both Linux (Ubuntu 16.04) and MacOS (10.12.6)

### ISSUE THREAD

**Issue by ghost** [iDroid-Project/OpeniBoot-toolchain#4]
Anyone know why this happens or how to fix it?

**Comment by nickpack** [comment]
The error will be output to the log file created by the script, I strongly expect that it'll be a dependency issue given the age of the project vs the age of the OS you're building on. The old gcc cross compile toolkit doesn't work on modern operating systems.

**Comment by ghost** [comment]
Ahh. Say if I tried on an old Ubuntu, would it work?

**Comment by nickpack** [comment]
I used to build on 12.04, though I have no idea if the third party compiler patches are still published for download - its been a VERY long time.

**Comment by ghost** [comment]
Okay, thanks.

I just tried on 9.04 and 9.10 and it failed on patching
